# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-09-01 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'grade',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=22),
        ),
        migrations.AlterField(
            model_name='student',
            name='s_name',
            field=models.CharField(default='jack', max_length=32),
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
        migrations.AddField(
            model_name='student',
            name='s_grade',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='App1.Grade'),
        ),
    ]
