# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-09-01 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_auto_20200901_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='s_grade',
        ),
    ]
